version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      commit-message:
        prefix: "chore(deps)"
      groups:
        dependencies:
          applies-to: version-updates
          update-types:
            - "minor"
            - "patch"
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      commit-message:
        prefix: "chore(deps)"
      groups:
        dependencies:
          applies-to: version-updates
          update-types:
            - "minor"
            - "patch"
