name: CI
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  pull_request:
jobs:
  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run test
permissions:
  contents: read
  pull-requests: write
